### ISSUE TITLE
I/O ports are not working properly

### ISSUE THREAD

**Issue by 849025143** [zymex22/Project-RimFactory-Revived#642] opened 2022-11-03 14:31 UTC
# Describe the bug

**To Reproduce**
Reproducibility: ?
1.  build add-port and out-port , close residents touch with storage
2. Residents cannot take items from the port ，When the equipment is turned on for interaction, it conflicts with nuclear power. Like Uranium fuel rod
3. All right, the storage device can only take out items, not store them

**Expected behavior**
Residents can store and retrieve items through the port

**Actual Behavior**
Residents can only store and conflict with certain items

**Screenshots**
No, Residents won't even touch it

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.4
 - PRF Version: 2.7.5(last)
 - Link to gist bug report: 
 - Type:
 - Severity:
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed:
 - Your modlist (if needed): 
 - Do you know what mod conflicts?: Nuclear energy and self

**Additional context**

**Comment by 849025143** [comment] 2022-11-03 14:43
Adv I/O port

**Comment by Sn1p3rr3c0n** [comment] 2022-11-03 14:54
@849025143 
Unfortunately I have a hard time understanding your report.
from what i understand the IO Ports are not working for you.
What types of IO Ports are affected? ("Normal" IO Ports, Advanced IO Ports)
how exactly are they not working for you?
Can you reproduce that issue? if yes what are the exact steps you take to reproduce the issue? (more detailed is better)
Please post a HugsLib log link (CTRL & F12) after observing your issue

Please Note for normal IO Ports:
- each IO Port can only interact with the linked Storage Unit
- For the Input the will only take items that are allowed in the linked Storage Unit
- For the Output, only the Items on-top may be accessed by Pawns
- You need to configure what items should be output
- It can only output items that are contained in the linked Storage Unit
- It is either an Input or an Output. Not both at the same time (you can switch that via a Gizmo)

Please Note for advanced IO Ports:
- each IO Port can only interact with the linked Storage Unit
- Pawns should automatically request items form them if that is quicker for them

**Comment by Sn1p3rr3c0n** [comment] 2022-11-09 09:56
@849025143 Please reply with the requested information.
If the Issue is resolved for you please also let us know.

If you do not reply I will have to close the Issue.

**Comment by Jacbo1** [comment] 2022-11-13 03:35
It might be the same issue I'm having. I just built my first CSU and Adv I/O port and the port cannot connect to the CSU and it threw an error in the console. The normal I/O port did work though.
```
System.NullReferenceException: Object reference not set to an instance of an object
  at Verse.GridsUtility.GetFirstItem (Verse.IntVec3 c, Verse.Map map) [0x00000] in <81af9f8a18324e17b286924a43555a7c>:0 
  at ProjectRimFactory.Storage.Building_StorageUnitIOPort.RefreshInput () [0x0001d] in <bb55ce7d370446bb86267289833f005c>:0 
  at ProjectRimFactory.Storage.Building_StorageUnitIOBase.Notify_NeedRefresh () [0x0001c] in <bb55ce7d370446bb86267289833f005c>:0 
  at ProjectRimFactory.Storage.Building_StorageUnitIOBase.ReceiveCompSignal (System.String signal) [0x00019] in <bb55ce7d370446bb86267289833f005c>:0 
  at Verse.ThingWithComps.BroadcastCompSignal (System.String signal) [0x00000] in <81af9f8a18324e17b286924a43555a7c>:0 
  at RimWorld.CompPowerTrader.set_PowerOn (System.Boolean value) [0x0007f] in <81af9f8a18324e17b286924a43555a7c>:0 
  at RimWorld.PowerNet.PowerNetTick () [0x0015e] in <81af9f8a18324e17b286924a43555a7c>:0 
  at RimWorld.PowerNetManager.PowerNetsTick () [0x00010] in <81af9f8a18324e17b286924a43555a7c>:0 
  at (wrapper dynamic-method) Verse.Map.Verse.Map.MapPostTick_Patch1(Verse.Map)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch2 (string)
(wrapper dynamic-method) Verse.Map:Verse.Map.MapPostTick_Patch1 (Verse.Map)
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch1 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch1 (Verse.Game)
Verse.Root_Play:Update ()

```

**Comment by Sn1p3rr3c0n** [comment] 2022-11-13 08:05
@Jacbo1 
I would prefer that if you are uncertain if your issue is the same one to rather open up a new one then Comment on a Existing one.
As i previously stated in this issue I'm uncertain what @849025143 is attempting to report, therefore those Issues should be treated as separate.

The Cold Storage Unit and Adv I/O port are currently not compatible, as noted in the Patchnotes (Steam & Github).
Therfore it is intended that you can't link them.
When reporting Errors please Post a HugsLib log (CTRL & F12) instead on Copy and Pasting the single Error.

**Comment by 849025143** [comment] 2022-11-18 15:48
> @Jacbo1 I would prefer that if you are uncertain if your issue is the same one to rather open up a new one then Comment on a Existing one. As i previously stated in this issue I'm uncertain what @849025143 is attempting to report, therefore those Issues should be treated as separate.
> 
> The Cold Storage Unit and Adv I/O port are currently not compatible, as noted in the Patchnotes (Steam & Github). Therfore it is intended that you can't link them. When reporting Errors please Post a HugsLib log (CTRL & F12) instead on Copy and Pasting the single Error.

"Adv I/O port" residents will not interact with it

**Comment by Sn1p3rr3c0n** [comment] 2022-11-18 15:58
@849025143 
Alright got it.

1. If you Can reproduce your issue, please post detailed steps on how to reproduce it.
2. Please Post a HugsLib Log after Observing your issue (CTRL & F12)

_**Regarding your edit**_
Is your issue that Pawns can not get items form the "Adv I/O port" ?
Or that pawns can place items into the "Adv I/O port"?

**Comment by Sn1p3rr3c0n** [comment] 2022-11-18 16:37
What do you mean by `turn off the machine interaction` ?

To work around the Language barriere you can maybe try to describe where this setting is on my provided Images.
![image](https://user-images.githubusercontent.com/68663281/202752393-5270b700-b942-4c4b-b3fe-3e3d0103508e.png)

![image](https://user-images.githubusercontent.com/68663281/202752645-2f565088-2f1e-4187-9107-96f0c1a02070.png)

As another Quick test option I have attached a Quick Test save file.

1. Extract the Zip File
2. Place `SampleSave.rws` in you Rimworld Save Folder `%appdata%\..\LocalLow\Ludeon Studios\RimWorld by Ludeon Studios\Saves`
3. Start Rimworld
4. Load the `SampleSave` Save
5. Undraft the Pawns

The Expected Outcome would be that the Pawns use the Advanced IO Port to garb a meal.

[SampleSave.zip](https://github.com/zymex22/Project-RimFactory-Revived/files/10043061/SampleSave.zip)

**General Advice**
- Use Rimpy to sort your Modlist (a bad load order can cause issues)

**Comment by 849025143** [comment] 2022-11-19 07:37
[Yuumi.zip](https://github.com/zymex22/Project-RimFactory-Revived/files/10046407/Yuumi.zip)
This is my save. Can you take a look at it for me? My Adv I/O port does not work properly.
I've sorted it. Use Raimpy

**Comment by Sn1p3rr3c0n** [comment] 2022-11-19 07:39
what was the result of the my provided test?
Please answer my questions, i Can't help you otherwise.

**Comment by 849025143** [comment] 2022-11-19 07:47
> 

No, it still doesn't seem to work properly. I loaded all mods.
![QQ截图20221119154553](https://user-images.githubusercontent.com/50692210/202840697-ce587572-0be0-4e2d-8cc9-85a4f6b93459.png)
![QQ截图20221119154604](https://user-images.githubusercontent.com/50692210/202840700-f72416c2-5c92-45b0-9817-0d595881ceea.png)

**Comment by Sn1p3rr3c0n** [comment] 2022-11-19 07:49
if you block the Patch to the DSU you need to enable the Can Reach Patch in the Settings

**Comment by 849025143** [comment] 2022-11-19 07:52
Even if I do not block, residents will not use Adv I/O. Is this normal?

**Comment by Sn1p3rr3c0n** [comment] 2022-11-19 07:54
If you load the Save I Provided will they grab the meal form the Port (Yes / No)?

**Comment by 849025143** [comment] 2022-11-19 08:13
> If you load the Save I Provided will they grab the meal form the Port (Yes / No)?

yes

**Comment by Sn1p3rr3c0n** [comment] 2022-11-19 08:26
okey good so the port should be working.
now you say if you want them to build something it doesn't work for you Right?
Please Check the following Things:
- The pawns are allowed to work on the task
- There is a path to the DSU or the CanReach Patch is active
- The Required Items are in the DSU
- The Port is the shortest path to the required thing
- The Port is not already reserved for something else

If you have confirmed all of the above points and it is still not working:
Load the save with **only** the the mods used in my sve.
Test again. Is it working now?

**Comment by 849025143** [comment] 2022-11-19 08:36
> okey good so the port should be working. now you say if you want them to build something it doesn't work for you Right? Please Check the following Things:
> 
> * The pawns are allowed to work on the task
> * There is a path to the DSU or the CanReach Patch is active
> * The Required Items are in the DSU
> * The Port is the shortest path to the required thing
> * The Port is not already reserved for something else
> 
> If you have confirmed all of the above points and it is still not working: Load the save with **only** the the mods used in my sve. Test again. Is it working now?

About your condition: meet

I found that it seemed to conflict with some items.
If I want granite bricks, they will work properly.
If my workbench needs something, it won't work properly. [look png file]
![QQ截图20221119163639](https://user-images.githubusercontent.com/50692210/202842435-fbfee0a6-dceb-4753-9346-a5c4168ae537.png)

**Comment by Sn1p3rr3c0n** [comment] 2022-11-19 08:52
That also should be working.
Please refer to my checklist:
- The pawns are allowed to work on the task
- There is a path to the DSU or the CanReach Patch is active
- The Required Items are in the DSU
- The Port is the shortest path to the required thing
- The Port is not already reserved for something else

If all of them apply then it should work with any recipe.
See [CraftingSample.zip](https://github.com/zymex22/Project-RimFactory-Revived/files/10046519/CraftingSample.zip) as an example. Undraft and they should use the Port to craft the Item shown in your Screenshot.

If that is working then this means that in your Test not all conditions where okey.
If that dose not work 
Load the save with only the the mods used in my sve.
Test again. Is it working now?

**Comment by 849025143** [comment] 2022-11-19 09:19
Well, my problem is solved.

Because I blocked the machine with a wall. I think it can only use "I/O port"

Thank you for your patience. Thank you very much.

**Comment by Sn1p3rr3c0n** [comment] 2022-11-19 09:50
Happy to help.

Closing issue.
User reports it is resolved

**Closed by Sn1p3rr3c0n** 2022-11-19 09:50 UTC
Labels: Need more Info
