### ISSUE TITLE
S.a.l can't be placed on some buildings

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#259] opened 2020-11-24 12:58 UTC
Report from Prismaa on discord.

S.A.L can't be placed on worker cell for:
- fab. bench
- biofuel refinery
- deep drill

and maybe more?
dunno what it is, but like Prismaa said on discord, can it in any ways be because of table size? or is it a matter of what `thingclass `  `placeworker` they use?

anyways might be looked at before release.
if it by any means make sense while looking for the problem? 
maybe if possible add research bench too, so we can think of a way to automate researching.
(maybe lock it behind `<CanResearch>` or something in mod extension, so its not everyone of them that can do it

**Comment by Sn1p3rr3c0n** [comment] 2020-11-24 16:06
as already corrected by `daemon976` and `Prismaa` on discord the **`fab. bench`** and the **`biofuel refinery`** are working as intended _(Can be placed)_
- [ ] there might be a need to improve the Graphics to prevent this


The **`deep drill`** is in fact not working with SAL. this is caused by the fact that the `deep drill` is not of `Building_WorkTabel`.
_ATM SAL only works with `Building_WorkTabel`_
- [ ] Check if its possible to support the `deep drill`

**Comment by zymex22** [comment] 2020-11-24 16:43
we could add same arrow for placement as belts using ? @lilwhitemouse

**Comment by Sn1p3rr3c0n** [comment] 2021-03-13 16:52
This issue should be resolved with #387

**Closed by Sn1p3rr3c0n** 2021-03-13 16:52 UTC
Labels: C#, enhancement
