### ISSUE TITLE
Plasma Drill Cannot Re-order Bills

### ISSUE THREAD

**Issue by BardezAnAvatar** [zymex22/Project-RimFactory-Revived#688] opened 2023-03-02 17:24 UTC
# Describe the bug
The Plasma Drill cannot re-order any of its bills when installed along side Better Workbench Management mod. When a bill is selected ON ONLY THIS STATION, it instead re-orders... colonists

**To Reproduce**
Reproducibility: ?
1. Install Better Workbench Management mod
2. Place a Plasma Drill (maybe other drills, too?)
3. Add several bills to the Plasma Drill
4. Try to drag the bills to re-order
5. Notice that colonists are moved instead. May have to drag the cursor to the bottom of the screen

**Expected behavior**
Bills should be movable

**Actual Behavior**
Bills will not be reorderable. Instead, the bill selection appears to redirect to colonists. See screenshots that show cursor over bills, but have floating colonist pawns dragged instead.

**Screenshots**
![screenshot10](https://user-images.githubusercontent.com/39980629/222502916-c82a05c6-eb1b-449e-af13-da31725febad.png)
![screenshot11](https://user-images.githubusercontent.com/39980629/222502919-b0bbc87d-94e0-46e0-b9d2-c0edab42c4ea.png)
![screenshot9](https://user-images.githubusercontent.com/39980629/222502925-2cc6d7ff-f94b-40d4-900f-ce6024fb8ddf.png)

**Rimworld (please complete the following information):**
 - RimWorld Version: latest (1.4)
 - PRF Version: latest
 - Link to gist bug report: 
 - Type:
 - Severity:
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: uncertain
 - Your modlist (if needed): Better Workbench Management
 - Do you know what mod conflicts?: Better Workbench Management

**Additional context**
Other workbenches and machines within PRF work properly (such as assemblers); I have noticed this bug for _several_ generations of PRF over the past few years. I want to say, anecdotally, that I used to see an index out of bounds of array error message when dragging bills but I am not able to reproduce that error reporting behavior at this time.

**Comment by BardezAnAvatar** [comment] 2023-03-02 17:25
Dang. Cursor not appearing in the screenshots. The cursor is over the top bill and moves up and down, roughly by pixels equal to the displaced colonist in the top bar.

**Comment by Sn1p3rr3c0n** [comment] 2023-03-02 18:41
it seems to reorder Colonists instead of Bills.
but since this works perfectly fine without `Better Workbench Management` i would assume the issue is on their end.
If i had to guess they either forgot to patch the correct Tab or their Patch broke.

**Comment by BardezAnAvatar** [comment] 2023-03-02 19:35
While possible, there is no patch in that mod for specific mods that I can see when looking at its source. It seems to be a highly irregular setup for the plasma drill.

I might take a look into both mods' source to see if I can track it down.

FYI, [link to a bug report over in Improved Workbenches' GitHub](https://github.com/Falconne/ImprovedWorkbenches/issues/104)

**Comment by Sn1p3rr3c0n** [comment] 2023-03-02 21:53
- [ ] recheck if we need `ProjectRimFactory.AutoMachineTool.ITab_Bills2` in addition to `ProjectRimFactory.SAL3.UI.ITab_SAL3Bills`

**Comment by Sn1p3rr3c0n** [comment] 2023-03-03 13:36
ccda0c5c93f59970eecc49a8a05ecf715763688f removes the additional BillTab.
The core issue still needs to be resolved by `Better Workbench Management`

**Comment by BardezAnAvatar** [comment] 2023-03-06 14:54
@Sn1p3rr3c0n I have a [patch](https://github.com/Falconne/ImprovedWorkbenches/pull/105) submitted over to `Better Workbench Management`; looks like it was building type and not bill type that was causing issues.

**Closed** 2023-03-28 09:20 UTC
