### ISSUE TITLE
Missing Items And Structures in Existing Save

### ISSUE THREAD

**Issue by AdamButtle15** [zymex22/Project-RimFactory-Revived#334] opened 2020-12-29 21:02 UTC
All Previous structures are missing in architect tab and on map, I have the new additions like the mine shaft.
I have some Items, Mostly new ones though.

They were fine before the latest update and patch.

I have The details from Player.log and the readout from the debug menu

[Player.log](https://github.com/zymex22/Project-RimFactory-Revived/files/5752153/Player.log)
[Debug Log.txt](https://github.com/zymex22/Project-RimFactory-Revived/files/5752154/Debug.Log.txt)

**Comment by Sn1p3rr3c0n** [comment] 2020-12-29 21:04
duplicate of #333

**Closed by Sn1p3rr3c0n** 2020-12-29 21:04 UTC

**Comment by AdamButtle15** [comment] 2020-12-29 21:05
oops sorry got a 404 error when posting the first one
