### ISSUE TITLE
I/O Port access toggle

### ISSUE THREAD

**Issue by TheyCallMeAmi** [zymex22/Project-RimFactory-Revived#447] opened 2021-05-13 21:11 UTC
**Is your feature request related to a problem? Please describe.**
Not exactly a problem, but I'm a little frustrated when using *Allow Tool* and then use the button "Allow everything" on the map, which includes items in I/O Ports, and I don't want colonists to access those items for building and such, and only SALs, etc.

**Describe the solution you'd like**
I'd like a toggle on output I/O Ports to auto-forbid (or just plain deny access like described below) items they hold so only machines can use them, and not colonists. (and possible auto allow/unforbid items that aren't

**Describe alternatives you've considered**
Haven't figured out any alternatives to this, other than to manually forbid the items I don't want allowed.

**Additional context**
Maybe also (if possible at all, toggleable would be perfect) so that the I/O ports can "hide" for the rest of machines except i.e. AutoMachineTool/SAL what they're holding, as in recipes don't reflect them existing in storage, even if they do, so I don't have to adjust bills to include extra product that are already in I/O ports in bills and such. I don't think it automatically adjusting bills based upon this would be performance efficient, but could also work.

Completely alterantively to this would be a toggle for each individual I/O port to allow pawn interaction (like the Digital storages have), if this included inputting items through I/O ports for pawns (maybe separate?), as I have some for collecting crafted items from machines. 

Essentially some pawns go to an I/O port to input to the storage rather than the digital storage itself/dedicated inputs, which sometimes make them travel further than necessary.

**Comment by Sn1p3rr3c0n** [comment] 2021-05-15 19:02
Duplicate of #394.

**Closed by Sn1p3rr3c0n** 2021-05-15 19:02 UTC
Labels: Request
