### ISSUE TITLE
(Bug report) S.A.L. Stat worker Null ref (random?) (EPOE Forked + addon)

### ISSUE THREAD

**Issue by turret001** [zymex22/Project-RimFactory-Revived#380] opened 2021-01-21 18:18 UTC
# Describe the bug
I built a Godly S.A.L. crafter and placed it in front of the Bionics Workbench from EPOE (Forked). At first, it did not work, so I restarted my game (quit the game completely) and it did a few crafting tasks successfully! after a few crafted items, it stopped again and outputted an error message on debug console.
Debug log: https://gist.github.com/1857ae4c112b3409a41ecc966ba7bf10 (at the very end of the log, I also added a comment under it)

**To Reproduce**
Reproducibility: ¯\_(ツ)_/¯
1. Build Godly S.A.L. crafter in front of the Bionics Workbench from EPOE
2. Put in 15 "Make advanced bionic leg" bill
3. Watch it craft a few or watch it fail

**Expected behavior**
It should craft all the bills without any issues.

**Actual Behavior**
It crafts a few (if you're lucky) and stops.

**Screenshots**
see the little bugger slackin' 
![image](https://user-images.githubusercontent.com/24281147/105392636-78352f80-5c2c-11eb-9738-9ed617f1863a.png)

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.2.2753
 - PRF Version: 2.5.4
 - Link to gist bug report: https://gist.github.com/1857ae4c112b3409a41ecc966ba7bf10
 - Type: I'm not sure
 - Severity: 1 out of 10 probably
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: I don't know but I guess not because then I wouldn't have the bionics workbench
 - Your modlist (if needed): 

<details>
  <summary>Modlist</summary>
  
Version: 1
Name: CR
Mods:
- Id: brrainz.harmony
  Name: Harmony
- Id: ludeon.rimworld
  Name: Core
- Id: ludeon.rimworld.royalty
  Name: Royalty
- Id: fluffy.modmanager
  Name: Mod Manager
- Id: tikubonn.anestheticgunmod
  Name: Anesthetic Gun MOD
- Id: tikubonn.anestheticturretmod
  Name: Anesthetic Turret MOD
- Id: automatic.autocleaner
  Name: Autocleaner
- Id: meltup.beautifuloutdoors
  Name: Beautiful Outdoors
- Id: frozensnowfox.betterspiketraps
  Name: '[FSF] Better Spike Traps'
- Id: automatic.bionicicons
  Name: Bionic icons
- Id: devdisigdu.bulk.components
  Name: Bulk Components
- Id: fuglypump.bulkstonecutting
  Name: Bulk Stonecutting
- Id: rwmt.multiplayer
  Name: Multiplayer
- Id: unlimitedhugs.hugslib
  Name: HugsLib
- Id: kapitanoczywisty.changemapedge
  Name: Change map edge limit
- Id: fluffy.colonymanager
  Name: Colony Manager
- Id: rselbo.dermalregenerator.1.0.0
  Name: DermalRegenerator
- Id: syrchalis.doormats
  Name: '[SYR] Doormats'
- Id: vat.epoeforked
  Name: Expanded Prosthetics and Organ Engineering - Forked
- Id: tarojun.epoeforked.allowdirectcrafting
  Name: 'EPOE-Forked: Allow direct crafting'
- Id: vat.epoeforkedroyalty
  Name: 'EPOE-Forked: Royalty DLC expansion'
- Id: wemd.fastmoisturepumps
  Name: '[WD] Fast Moisture Pumps'
- Id: firefoxpdm.rainbeausfishing
  Name: '[RF] Fishing'
- Id: frozensnowfox.growableambrosia
  Name: '[FSF] Growable Ambrosia'
- Id: smuffle.harvestorganspostmortem
  Name: Harvest Organs Post Mortem
- Id: orion.hospitality
  Name: Hospitality
- Id: petetimessix.simplesidearms
  Name: Simple sidearms
- Id: netrve.usemelee
  Name: Hunters Use Melee!
- Id: navyseal5.infestationbait
  Name: InfestationBait
- Id: avius.locks
  Name: Locks
- Id: ratys.madskills
  Name: Mad Skills
- Id: wofl.morefurnitureupdated
  Name: More Furniture [1.1 + 1.2]
- Id: 4loris4.morelinkables
  Name: More Linkables
- Id: paradox.morevanillaturrets
  Name: More Vanilla Turrets 1.1
- Id: hobtook.mortaraccuracy
  Name: Mortar Accuracy
- Id: maszopok.narco
  Name: Narco
- Id: dingo.noforcedslowdown
  Name: No Forced Slowdown
- Id: ogre.ogrestack
  Name: OgreStack
- Id: pathavoid.kv.rw
  Name: '[KV] Path Avoid'
- Id: fluffy.pharmacist
  Name: Pharmacist
- Id: mlie.pickupandhaul
  Name: Pick Up And Haul (Continued)
- Id: mlie.plasteelsurgery
  Name: Plasteel Surgery (Continued)
- Id: avius.prisonlabor
  Name: Prison Labor
- Id: spdskatr.projectrimfactory
  Name: Project RimFactory Revived
- Id: ogliss.thewhitecrayon.quarry
  Name: Quarry 1.1
- Id: mlie.psreconditioningpod
  Name: '[PS] Reconditioning Pod (Continued)'
- Id: acruid.repairbench
  Name: Repair Workbench
- Id: uuugggg.replacestuff
  Name: Replace Stuff
- Id: notfood.researchpal
  Name: ResearchPal
- Id: rimfridge.kv.rw
  Name: '[KV] RimFridge'
- Id: weilbyte.rimrpc
  Name: RimRPC - RichPresence
- Id: mlie.roadsoftherim
  Name: Roads of the Rim (Continued)
- Id: dhultgren.smarterconstruction
  Name: Smarter Construction
- Id: la.soakingwet
  Name: Soaking Wet is a Good Thing
- Id: unlimitedhugs.allowtool
  Name: Allow Tool
- Id: marvinkosh.sometimesraidsgowrong
  Name: Sometimes Raids Go Wrong
- Id: linkolas.stabilize
  Name: Stabilize
- Id: void.szfloors
  Name: SZ_Floors
- Id: gt.sam.tilledsoil
  Name: Tilled Soil
- Id: tradingspot.kv.rw
  Name: '[KV] Trading Spot'
- Id: owlchemist.undergroundpowerconduits
  Name: Underground Power Conduits
- Id: vanillaexpanded.vfepower
  Name: Vanilla Furniture Expanded - Power
- Id: sickboywi.vault.onepointone
  Name: Vault
- Id: dismarzero.vgp.vgpgardenfabrics
  Name: VGP Garden Fabrics
- Id: dismarzero.vgp.vgpgardenmedicine
  Name: VGP Garden Medicine
- Id: dismarzero.vgp.vgpvegetablegarden
  Name: VGP Vegetable Garden
- Id: herigony.mapedittools
  Name: Map Edit Tools
- Id: neronix17.embrasures
  Name: '[O21] Seamless Embrasures'
- Id: orion.gastronomy
  Name: Gastronomy
- Id: co.uk.epicguru.whatsthatmod
  Name: What's That Mod
- Id: odeum.wmbp
  Name: World Map Beautification Project
- Id: fluffy.worktab
  Name: Work Tab
- Id: mlie.fencesandfloors
  Name: Fences And Floors (Continued)
- Id: jebo.noannoyances
  Name: Annoyance Remover v0.07
- Id: falconne.aff
  Name: Avoid Friendly Fire
- Id: fluffy.blueprints
  Name: Blueprints
- Id: jp.perfectpathing
  Name: Perfect Pathfinding
  
</details>

 - Do you know what mod conflicts?:  this one: https://steamcommunity.com/sharedfiles/filedetails/?id=1949064302

**Additional context**
I also have 2 addon mods for EPOE, here they are:
https://steamcommunity.com/sharedfiles/filedetails/?id=2024879910
https://steamcommunity.com/sharedfiles/filedetails/?id=2008970276

**Comment by Sn1p3rr3c0n** [comment] 2021-01-21 18:21
this is a duplicate of #259 
closing.

**Comment by Sn1p3rr3c0n** [comment] 2021-01-21 19:01
The rull ref seems to randomly occur. can causes the progress / work to halt as the work amount cant be determinant.
https://gist.github.com/HugsLibRecordKeeper/1857ae4c112b3409a41ecc966ba7bf10
```
System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.StatWorker.GetValueUnfinalized (RimWorld.StatRequest req, System.Boolean applyPostProcess) [0x00373] in <d72310b4d8f64d25aee502792b58549f>:0 
  at RimWorld.StatWorker.GetValue (RimWorld.StatRequest req, System.Boolean applyPostProcess) [0x00043] in <d72310b4d8f64d25aee502792b58549f>:0 
  at RimWorld.StatWorker.GetValueAbstract (Verse.BuildableDef def, Verse.ThingDef stuffDef) [0x00009] in <d72310b4d8f64d25aee502792b58549f>:0 
  at RimWorld.StatExtension.GetStatValueAbstract (Verse.BuildableDef def, RimWorld.StatDef stat, Verse.ThingDef stuff) [0x00006] in <d72310b4d8f64d25aee502792b58549f>:0 
  at Verse.RecipeDef.WorkAmountTotal (Verse.ThingDef stuffDef) [0x00020] in <d72310b4d8f64d25aee502792b58549f>:0 
  at ProjectRimFactory.AutoMachineTool.Building_AutoMachineTool.<TryStartWorking>b__37_0 (System.Tuple`2[T1,T2] tuple) [0x00120] in <1fd014ddbd464bcebc65195fc7f65154>:0 
  at ProjectRimFactory.AutoMachineTool.Option`1[T].Select[TO] (System.Func`2[T,TResult] func) [0x00010] in <1fd014ddbd464bcebc65195fc7f65154>:0 
  at ProjectRimFactory.AutoMachineTool.Building_AutoMachineTool.TryStartWorking (ProjectRimFactory.AutoMachineTool.Building_AutoMachineTool& target, System.Single& workAmount) [0x00054] in <1fd014ddbd464bcebc65195fc7f65154>:0 
  at ProjectRimFactory.AutoMachineTool.Building_Base`1[T].Ready () [0x00051] in <1fd014ddbd464bcebc65195fc7f65154>:0 
  at ProjectRimFactory.AutoMachineTool.Building_BaseRange`1[T].Ready () [0x00001] in <1fd014ddbd464bcebc65195fc7f65154>:0 
  at ProjectRimFactory.AutoMachineTool.Building_AutoMachineTool.Ready () [0x00008] in <1fd014ddbd464bcebc65195fc7f65154>:0 
  at ProjectRimFactory.AutoMachineTool.MapTickManager.Exec (System.Action act) [0x00002] in <1fd014ddbd464bcebc65195fc7f65154>:0 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
```

**Comment by turret001** [comment] 2021-01-21 19:04
should I create an issue on EPOE github or is it something you guys can fix?

**Comment by Sn1p3rr3c0n** [comment] 2021-01-21 22:22
[EPOE-Forked: Allow direct crafting](https://steamcommunity.com/sharedfiles/filedetails/?id=2024879910) dos not seem to set a workamount for it's Bills.

Not really sure about the nobo checks but b92ee5f should resolve the issue.

**Closed** 2021-01-21 22:35 UTC
Labels: Incompatibility, nobo's code
