### ISSUE TITLE
Spacer Animal Harvester collection zone incorrect

### ISSUE THREAD

**Issue by JulianSkies** [zymex22/Project-RimFactory-Revived#295] opened 2020-12-13 01:45 UTC
# Describe the bug
The Center Square and Facing Rectangle area selections of the Animal Harvester are off-center.

**To Reproduce**
1. Put down Spacer Animal Harvester
2. On Settings tab, change area to Circle Type
3. On Overclock tab, change the range
4. On Settings tab, change area to either Center Square or Facing Rectangle.
5. Center Square/Facing Rectangle areas are now centered on the lower-left corner of the Harvester, just like the way the Circle Type works.

**Expected behavior**
Changing the area types shouldn't alter their centering to that of area types

**Actual Behavior**
Centering got changed.

**Screenshots**
![Offcenter Square](https://user-images.githubusercontent.com/20136904/102000986-8c038280-3ccb-11eb-8437-630f22fab050.png)

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.2
 - PRF Version: Latest as of 12/12/2020 at 19:43 EST

**Comment by Sn1p3rr3c0n** [comment] 2020-12-13 14:43
The issue is that all Calculations for ranges (even Vanilla) are not correctly considering the case of **"Even-sized"** Buildings with rotation.

**"Even-sized"** refers to all buildings where the at least one side has an even number of cells. This leads to that Situation where the ideal Center is at a space between cells.
In that case the game chooses a nearby cell as `Center` in case of a 2x2 this is the bottom left.

---
 
**To Reproduce**
There is a vital missing step that is to rotate the `FacingRect`. without that the issue will not occur

---
**TODO**
- [ ] Fix the oversight in the calculations

**wont fix**
Circle center is in the bottom left corner. _the center is not a cell so we need to pick something... --> going with the official rimworld calculations_

**Closed** 2020-12-15 19:58 UTC
