### ISSUE TITLE
Apothecary

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#27] opened 2020-04-30 07:26 UTC
Found a bug when using this mod togheter with Apothecary. When the drones in the cultivator is going to sow Belladona and Tummeric, they just keep sowing and sowing and harvesting at the same time. The plant grows up Immediately.So they sow and harvest at the same time.
So I moved the cultivator to another spot and let it work on ingame crops insteed :P

**Comment by zymex22** [comment] 2020-07-23 11:30
Got a few comments on this on Steam, apparently Apothecary will have some problems with cultivator haven't tested it yet, and dont know if its a priority or not, so ill just leave this here.

**Comment by Sn1p3rr3c0n** [comment] 2020-08-02 13:27
For documentation: i am unable to reproduce this issue. i would assume it was fixed by Apothecary itself.

**Closed** 2020-10-12 18:44 UTC
Labels: Incompatibility, Mod support
