### ISSUE TITLE
I/O Pushers Breaking

### ISSUE THREAD

**Issue by TheyCallMeAmi** [zymex22/Project-RimFactory-Revived#438] opened 2021-04-24 00:11 UTC
# Describe the bug
Whenever I try to place an I/O Pusher facing a Deep Refridgerator from using both LWM's Deep storage + Rimfridge, I get this error, and the pusher doesn't work at all, it literally doesn't even connect to a power grid, and neither can I select what it should push from the storage tab, which doesn't show up either.

**To Reproduce**
Reproducibility: Seems to be consistent.
1. Place an I/O Pusher facing a deep fridge

**Expected behavior**
I... expect it to work as intended like with everything else?

**Actual Behavior**
Breaks completely and doesn't do anything.

**Rimworld (please complete the following information):**
 - RimWorld Version: Latest
 - PRF Version: Latest
 - Link to gist bug report: 
 - Type: Bug
 - Severity: Mild inconvenience at best as an easy workaround is just using an I/O Port and an item puller, tho that ofc does use more space.
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: Can't really test as it is mod related
 - Your modlist (if needed): (Very long, please ask if needed)
 - Do you know what mod conflicts?: It's mentioning the Haul Explicitly mod in the error, but, I don't know.

**Additional context**

Root level exception in OnGUI(): System.NullReferenceException: Object reference not set to an instance of an object
  at ProjectRimFactory.Storage.Building_StorageUnitIOBase.get_ForbidPawnInput () [0x0001f] in <4388fe5ce4624a84bb6eda7dd8b37192>:0 
  at ProjectRimFactory.Common.HarmonyPatches.Patch_Building_Storage_Accepts.Prefix (RimWorld.Building_Storage __instance, Verse.Thing t, System.Boolean& __result) [0x00019] in <4388fe5ce4624a84bb6eda7dd8b37192>:0 
  at (wrapper dynamic-method) RimWorld.Building_Storage.RimWorld.Building_Storage.Accepts_Patch1(RimWorld.Building_Storage,Verse.Thing)
  at RimWorld.StoreUtility.IsInValidBestStorage (Verse.Thing t) [0x0000a] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at HaulExplicitly.HaulablesUtilities.ShouldBeHaulableExt (RimWorld.ListerHaulables lh, Verse.Thing t, System.Boolean will_toggle_haul_des) [0x0000e] in <c1fdb01f793b4e758313202d76b1c605>:0 
  at HaulExplicitly.ListerHaulables_ShouldBeHaulable_Patch.Prefix (Verse.Thing t, RimWorld.ListerHaulables __instance, System.Boolean& __result) [0x00001] in <c1fdb01f793b4e758313202d76b1c605>:0 
  at (wrapper dynamic-method) RimWorld.ListerHaulables.RimWorld.ListerHaulables.ShouldBeHaulable_Patch1(RimWorld.ListerHaulables,Verse.Thing)
  at RimWorld.ListerHaulables.Check (Verse.Thing t) [0x00000] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimWorld.ListerHaulables.RecalcAllInCell (Verse.IntVec3 c) [0x00019] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimWorld.ListerHaulables.Notify_SlotGroupChanged (RimWorld.SlotGroup sg) [0x00016] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimWorld.HaulDestinationManager.AddHaulDestination (RimWorld.IHaulDestination haulDestination) [0x000bf] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at (wrapper dynamic-method) Verse.Thing.Verse.Thing.SpawnSetup_Patch0(Verse.Thing,Verse.Map,bool)
  at Verse.ThingWithComps.SpawnSetup (Verse.Map map, System.Boolean respawningAfterLoad) [0x00000] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at (wrapper dynamic-method) Verse.Building.Verse.Building.SpawnSetup_Patch2(Verse.Building,Verse.Map,bool)
  at (wrapper dynamic-method) RimWorld.Building_Storage.RimWorld.Building_Storage.SpawnSetup_Patch1(RimWorld.Building_Storage,Verse.Map,bool)
  at ProjectRimFactory.Storage.Building_StorageUnitIOBase.SpawnSetup (Verse.Map map, System.Boolean respawningAfterLoad) [0x00001] in <4388fe5ce4624a84bb6eda7dd8b37192>:0 
  at ProjectRimFactory.Storage.Building_IOPusher.SpawnSetup (Verse.Map map, System.Boolean respawningAfterLoad) [0x00001] in <4388fe5ce4624a84bb6eda7dd8b37192>:0 
  at (wrapper dynamic-method) Verse.GenSpawn.Verse.GenSpawn.Spawn_Patch4(Verse.Thing,Verse.IntVec3,Verse.Map,Verse.Rot4,Verse.WipeMode,bool)
  at (wrapper dynamic-method) RimWorld.Designator_Build.RimWorld.Designator_Build.DesignateSingleCell_Patch1(RimWorld.Designator_Build,Verse.IntVec3)
  at (wrapper dynamic-method) Verse.DesignatorManager.Verse.DesignatorManager.ProcessInputEvents_Patch2(Verse.DesignatorManager)
  at RimWorld.MapInterface.HandleMapClicks () [0x0000f] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimWorld.UIRoot_Play.UIRootOnGUI () [0x00089] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at (wrapper dynamic-method) Verse.Root.Verse.Root.OnGUI_Patch1(Verse.Root)
Verse.Log:Error(String, Boolean)
Verse.Root:Verse.Root.OnGUI_Patch1(Root)

**Comment by Sn1p3rr3c0n** [comment] 2021-04-24 07:14
Only appeasers to occur on pawn interaction.

**Comment by TheyCallMeAmi** [comment] 2021-04-24 22:44
For me it happens whenever I place one, and as I mentioned it breaks completely.

**Comment by Sn1p3rr3c0n** [comment] 2022-05-20 10:20
@TheyCallMeAmi 
Going back to this report I am unable to reproduce it.
Should you stille face this issue you may reopen if you provide a HugsLib Log & an detailed description on how to reproduce.

Closing

**Closed by Sn1p3rr3c0n** 2022-05-20 10:20 UTC
