### ISSUE TITLE
[Mine Shaft] Production Bug

### ISSUE THREAD

**Issue by XTCProbstA2** [zymex22/Project-RimFactory-Revived#653] opened 2022-11-19 04:22 UTC
# Describe the bug
With the mods I have, I just make a bill. Select coal under the [Mine Shaft] bill tab. Then switch the bill from [Do x Times] to [Do untill you have x] and it bugs out then. Will not let me reopen the bill tab on the [Mine Shaft].

**Expected behavior**
Quarry/mine coal from the [Mine Shaft].

**Actual Behavior**
Pawn working on bill from [Mine Shaft], Quarrying/mining out nothing from [Mine Shaft].

**Screenshots**
In Order. **Group 1**
1. https://imgur.com/MMDrEwN
2. https://imgur.com/ycAJ5lF
3. https://imgur.com/EBlb1BL
In Order **Group 2**
1. https://imgur.com/iZWWySd
2. https://imgur.com/X9ysdVI
3. https://imgur.com/HO9lOSl

**Rimworld (please complete the following information):**
 - RimWorld Version: **Newest 1.3 version**
 - PRF Version: using **1.3**
 - Link to gist bug report: **https://gist.github.com/HugsLibRecordKeeper/83287ad654132470a7b1fcd4d4d83ed6**
 - Type: **"IDK?"**
 - Severity: **Game becomes unplayable. "I'm not sure if this is what you guys meant"**
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: **I'm using the [Mine Shaft] Production from this mod.**
 - Your modlist (if needed): **https://steamcommunity.com/sharedfiles/filedetails/?id=2890370957**
 - Do you know what mod conflicts?: **Unknown. I'm assuming any mod relating to coal.**

**Comment by Sn1p3rr3c0n** [comment] 2022-11-19 06:37
I tested this in 1.4 & 1.3 and everything works as expected.

This is probably caused by a Modconflict.

Base on the Error causing this:
```
Exception filling tab RimWorld.ITab_Bills: System.NullReferenceException: Object reference not set to an instance of an object
  at (wrapper dynamic-method) Verse.RecipeWorkerCounter.Verse.RecipeWorkerCounter.CountProducts_Patch1(Verse.RecipeWorkerCounter,RimWorld.Bill_Production)
  at (wrapper dynamic-method) RimWorld.Bill_Production.RimWorld.Bill_Production.ShouldDoNow_Patch1(RimWorld.Bill_Production)
  at (wrapper dynamic-method) RimWorld.Bill.RimWorld.Bill.DoInterface_Patch1(RimWorld.Bill,single,single,single,int)
  at RimWorld.BillStack.DoListing (UnityEngine.Rect rect, System.Func`1[TResult] recipeOptionsMaker, UnityEngine.Vector2& scrollPosition, System.Single& viewHeight) 
  at RimWorld.ITab_Bills.FillTab ()
  at Verse.InspectTabBase+<>c__DisplayClass14_0.<DoTabGUI>b__0 ()  
```
 I would suspect it is caused by `RimForge`. Can you try without that mod?

**Comment by Sn1p3rr3c0n** [comment] 2022-11-19 07:16
btw there is no need to report your issue on multiple platforms...

**Comment by Sn1p3rr3c0n** [comment] 2022-11-19 07:28
anyway the issue is caused by a null ref to `PRF_Coal`. 
Materials alone works fine.
You need to find the mod causing that issue and report it to them.

**Comment by Sn1p3rr3c0n** [comment] 2022-11-22 11:46
Closing issue -> caused by error in a unknown mod

**Closed by Sn1p3rr3c0n** 2022-11-22 11:46 UTC
Labels: Need more Info
