### ISSUE TITLE
i am so sorry for my English  so maybe you can.t understand

### ISSUE THREAD

**Issue by binglanziyu** [zymex22/Project-RimFactory-Revived#581] opened 2022-05-10 16:57 UTC
![4d146d52eaedb9fb718513a5c48adc8d_88749cdfa9ec8a130ee16f37b203918fa2ecc0c3_tbpicau=2022-05-13-05_1df12788b2e4481934b986b401760142](https://user-images.githubusercontent.com/105308311/167680801-14108826-e204-4c7f-bfb2-b6be1382d1d6.jpg)

when  only one space for many people or robot to enter the factory  and use io  it will fail

![33c915a862fbffaa8fac6de8f9e08250_3a856a1190ef76c6686ac2fcd816fdfaae516702_tbpicau=2022-05-13-05_e02756854a6fe8f46f7bab9ed6f4cb5a](https://user-images.githubusercontent.com/105308311/167681547-d577319a-576f-4c98-a881-3971fb3d8856.jpg)

and

![2294d583cd5368949bb8c448b29f03c1_0e4bfef082025aaf90b7471cbeedab64024f1a3c_tbpicau=2022-05-13-05_c5361f98b981361e5665efbc3fec6f6d](https://user-images.githubusercontent.com/105308311/167681571-62416182-0f36-48eb-b9fb-7cd1802df3e4.jpg)
and

![331da03fdbb517d21ff41a0a2eee4084_2d8bda2c11dfa9ece7e36fc027d0f703938fc1f5_tbpicau=2022-05-13-05_31cd2b687e3b5ef408af3c6d1258ad9b](https://user-images.githubusercontent.com/105308311/167681607-4df88b9f-c177-4e57-a33a-f5d77f07beac.jpg)

but  when i  destroy buildings   like  this  it will be ok!    oh year   ヽ(≧□≦)ノ
![image](https://user-images.githubusercontent.com/105308311/167682255-7a036e06-e30b-4569-8f7e-d1a35f06a2dd.png)

**Comment by Sn1p3rr3c0n** [comment] 2022-05-10 16:59
please post a HugsLib Log (CTRL & F12)

**Comment by binglanziyu** [comment] 2022-05-10 17:03
[Player.log](https://github.com/zymex22/Project-RimFactory-Revived/files/8663581/Player.log)
is it right？

**Comment by Sn1p3rr3c0n** [comment] 2022-05-10 17:04
Please press the `CTRL & F12` Key combination.
Follow the dialog to upload a HugsLib Log
Post the link here.

**Comment by binglanziyu** [comment] 2022-05-10 17:17
https://gist.github.com/5f121bf9280d130d050b33b5e97a36ef

**Comment by binglanziyu** [comment] 2022-05-10 17:20
line 7870

**Comment by Sn1p3rr3c0n** [comment] 2022-05-10 17:37
This issue is **not** caused by this mod.
The `NullReferenceException` is trigged by the Vanilla `Verse.Thing.Smeltable` getter.

This means that this issue is likely caused by either
- You Rimworld Game Files being corrupt → If you are on Steam use the `Verify integrity of game files` otherwise re-download Rimwold.
- The mod that added the item that you are attempting to haul messed up → Report it to them
- The removal of a mod that added Materials mid save → ...

As general advice I recommend that you sort you mod list (RimPy)

Closing issue.

**Closed by Sn1p3rr3c0n** 2022-05-10 17:37 UTC
Labels: Need more Info
