### ISSUE TITLE
Drones may not notice a change to forbidden

### ISSUE THREAD

**Issue by Vectorial1024** [zymex22/Project-RimFactory-Revived#600] opened 2022-07-09 14:16 UTC
# Describe the bug
As title. Drones are interacting with forbidden items/buildings, such as picking up from them/using them.

**To Reproduce**
There are a few cases:

## First case: picking up forbidden items
1. Construct a smart hopper, and let it be: preferred priority, stores steel
2. Set up a storage zone within range of smart hopper and let it be: critical priority, stores steel
3. Set up a caretaker drone station and give it some drones
4. Drones now pick up steel from hopper and places it back to the storage zone, which immediately sends the steel baack to the hopper
- Expected behavior: dont pick up from the smart hopper
- Actual behavior: picks up from smart hopper

## Second case: using forbidden buildings
1. Let a pawn scan an underground deposit
2. Build a deep drill at the deposit, set up power, etc; let the pawns mine them out
3. "Resource exhausted; deep drill is now set to forbidden"
4. Drones decide to continue using the deep drill and begins drilling up many stone chunks
- Expected behavior: dont use the deep drill (if forbidden)
- Actual behavior: uses the deep drill regardless if is forbidden

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.3.3389
 - PRF Version: ??? (Steam latest as of writing)
 - Link to gist bug report: /
 - Type: ?
 - Severity: Moderate
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: (/)
 - Your modlist (if needed): (/)
 - Do you know what mod conflicts?: seems no conflict?

**Additional context**
/

**Comment by Sn1p3rr3c0n** [comment] 2022-07-09 20:39
I am unable to reproduce your report regarding case 1.
Please attach a HugsLib Log.

for Case 2 it appears that dorone fail to notice the switch to forbidden

**Comment by Vectorial1024** [comment] 2022-07-10 03:56
Hmmm, maybe I looked wrongly, but I feel like I saw constructions drones pulling items from the smart hoppers to build stuff etc. I can't reproduce case 1 too.

**Comment by Sn1p3rr3c0n** [comment] 2022-07-11 16:59
Set it to Low Priority as this only occurs in one specific instance and could be fixed by a quick lockdown & re-activation.

This issue appears to occur as Drones are don't interrupt their current job.

**Comment by Sn1p3rr3c0n** [comment] 2024-02-23 13:01
So far I only noticed the `expiryInterval` on the Mine Job set at 20000
Deep drilling would be on 1500

_my concern with removing the removal of `expiryInterval` would be the performance impact of the additional job searches._
_So far it seems that there are no crazy low values in use for that, so it should not be an issue_

**Closed** 2024-02-23 18:14 UTC
Labels: bug, Low Priority
