### ISSUE TITLE
Meat Grinder keep searching

### ISSUE THREAD

**Issue by SilvioCf27** [zymex22/Project-RimFactory-Revived#535] opened 2021-11-10 18:32 UTC
I have a meat grinder, a dead animal, a bill and it don't do nothing, keep searching.

To Reproduce
Reproducibility: maybe

have a meat grinder
have a dead animal in collect zone(white zone)
done
Expected behavior
Transform the animal into raw food.

Actual Behavior
Can't find the animal.

**Comment by Sn1p3rr3c0n** [comment] 2021-11-10 18:35
Please attach a Hugs Lib log. (CTRL & F12)
some images of your setup and the bills tab might also help.

**Comment by Kevsnz** [comment] 2021-11-13 14:54
Yeah, it's really easily reproducible.

1. Make pretty much barebones Rimworld run with HugsLib and Project Rimfactory. Latest versions.
2. Start 'Rich explorer' scenario.
2. Devmode in minified meat grinder and vanometric cell. Install them near each other.
3. Create bill 'Butcher creature' - 'Do forever'.
4. Create stockpile around meat grinder, allow only corpses.
5. Shot some animal and haul it to stockpile.
6. Exception will pop up within a second after placing animal to stockpile.

Here is a log: [HugsLib Log](https://git.io/JXp1X)
And here is the setup:
![Setup Pic](https://user-images.githubusercontent.com/15689588/141648192-507809be-8bfb-446d-862c-87d19d034cae.PNG)

Hope this will help finding the issue.

**Comment by Sn1p3rr3c0n** [comment] 2021-11-13 15:29
@Kevsnz 
Unfortunately I am unable to reproduce your report even with the exact same modlist and following the steps provided by you.

Please Validate the integrity of you Rimworld files.
For steam you can find this under `Rimworld`  `Properties` --> `Local Files` --> `Verify integrity of game files`

after that please also `unsubscribe` & `resubscribe` for PRF to force an update.

please let me know if the issue persists for you after that

**Comment by Kevsnz** [comment] 2021-11-14 05:09
@Sn1p3rr3c0n
OK, after messing with rimworld installation and mods I got it to work.
The issue was that steam for some reason did push *some* of the updated files but not others, namely ProjectRimFactory.dll.
So after resub and quick test in my big savegame everything looks to be working a-OK.
Maybe other players have the same issue too.
Thanks for help.

**Comment by Sn1p3rr3c0n** [comment] 2021-11-14 06:06
Closing.
Issue caused by outdated PRF and was fixed with a resub on steam

**Closed by Sn1p3rr3c0n** 2021-11-14 06:06 UTC
