### ISSUE TITLE
 (Bug report) Mod conflict Universal Fermenter HSK version

### ISSUE THREAD

**Issue by AtmosDragon** [zymex22/Project-RimFactory-Revived#603] opened 2022-07-13 22:48 UTC
Rimworld version:1.3.3387.
The output in the rimfactory mechanisms does not work due to a conflict with the Universal Fermenter built into Core HSK, log:
Ошибка создания элементов для Thing_PRF_StoneWorks872976: System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта
в (динамический метод оболочки) UniversalFermenterSK.GenRecipe_PostProcessProductPatch.UniversalFermenterSK.GenRecipe_PostProcessProductPatch.Prefix_Patch0(Verse&World. )
at (динамический метод оболочки) Verse.GenRecipe.Verse.GenRecipe.PostProcessProduct_Patch3(Verse.Thing,Verse.RecipeDef,Verse.Pawn,RimWorld.Precept_ThingStyle)
в DMD<>?-565695488.Verse.GenRecipe+d__0.MoveNext_Patch0 ( Verse.GenRecipe+d__0 this) [0x00232] в <90b76ada8d384ce19799938a1e242dab>:0
в System.Collections.Generic.List1[T]..ctor (System.Collections.Generic.IEnumerable1[T] collection) [0x00077] in :0
at ProjectRimFactory.Common.Patch_GenRecipe_MakeRecipeProducts_BonusYield+d__0.MoveNext () [0x00028] in <30c47be6e7b241788eb2c5cbb3c124a8>:0
at ProjectRimFactory.SAL3.Things.Assemblers.Building_ProgrammableAssembler.ProduceItems () [0x00090] in <30c47be6e7b241788eb2c5cbb3c124a8>:0
at (wrapper dynamic-method) ProjectRimFactory.SAL3.Things.Assemblers.Building_ProgrammableAssembler.ProjectRimFactory.SAL3.Things.Assemblers.Building_ProgrammableAssembler.Tick_Patch0(ProjectRimFactory.SAL3.Things.Assemblers.Building_ProgrammableAssembler)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(динамический метод-оболочка) Verse.Log:Verse.Log.Error_Patch4 (строка)
(динамический метод-оболочка) ProjectRimFactory.SAL3.Things.Assemblers.Building_ProgrammableAssembler:ProjectRimFactory.SAL3.Things.Assemblers.Building_ProgrammableAssembler.Tick_Patch0 (ProjectRimFactory.SAL3.Things.Assemblers.Building_ProgrammableAssembler)
Verse.TickList:Tick ()
(динамический метод-оболочка ) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch1 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(динамический метод-оболочка) Verse.Game:Verse.Game.UpdatePlay_Patch1 (Verse.Game)
Verse.Root_Play:Update ()
P. S: the HSK developers refused to do anything.

**Comment by Sn1p3rr3c0n** [comment] 2022-07-14 06:13
Duplicate of #554 and #519

In short this issue is cause by the altered version of `UniversalFermenter` called `UniversalFermenterSK` included in your Modpack.
We can not fix this issue. it must be fixed by the authors of HSK.

**Closed by Sn1p3rr3c0n** 2022-07-14 06:13 UTC
