### ISSUE TITLE
Possible mod conflict

### ISSUE THREAD

**Issue by sdfg2** [zymex22/Project-RimFactory-Revived#812] opened 2024-09-01 17:08 UTC
Trying to make a revolver to test the quantum assembler prime. Work countdown starts, but no item is produce.

Log says this:

```Error producing items for Thing_PRF_TypeTwoAssembler_II3427598: System.NullReferenceException: Object reference not set to an instance of an object
[Ref AC438558]
 at ImP.ImpCore.GetRoleEffectQualityOffset (Verse.Pawn worker) [0x00007] in <d2367ec190634db0bac6793f3c680077>:0 
 at ImP.ImpCore.GetFixedThoughtDefOf (Verse.Pawn worker, Verse.RecipeDef recipeDef, Verse.Thing thing) [0x00039] in <d2367ec190634db0bac6793f3c680077>:0 
 at ImP.PatchMakeRecipeProducts+<Postfix>d__0.MoveNext () [0x00059] in <d2367ec190634db0bac6793f3c680077>:0 
 at <0x1acba43d210 + 0x002c9> <unknown method>
 at ProjectRimFactory.Common.Patch_GenRecipe_MakeRecipeProducts_BonusYield+<Postfix>d__0.MoveNext () [0x00028] in <e85aa4e119764ab3ac1cf233e1b3a454>:0 
 at ProjectRimFactory.SAL3.Things.Assemblers.Building_ProgrammableAssembler.ProduceItems () [0x000b6] in <e85aa4e119764ab3ac1cf233e1b3a454>:0 
 at ProjectRimFactory.SAL3.Things.Assemblers.Building_ProgrammableAssembler.Tick () [0x000e4] in <e85aa4e119764ab3ac1cf233e1b3a454>:0 
     - TRANSPILER PerformanceOptimizer.Main: IEnumerable`1 PerformanceOptimizer.Optimization_FasterGetCompReplacement:Transpiler(IEnumerable`1 instructions, MethodBase method)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Log.Error_Patch5 (string)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:ProjectRimFactory.SAL3.Things.Assemblers.Building_ProgrammableAssembler.Tick_Patch0 (ProjectRimFactory.SAL3.Things.Assemblers.Building_ProgrammableAssembler)
ProjectRimFactory.SAL3.Things.Assemblers.Special.Building_Assembler_Learning:Tick ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.TickList.Tick_Patch2 (Verse.TickList)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.TickManager.DoSingleTick_Patch6 (Verse.TickManager)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.TickManager.TickManagerUpdate_Patch0 (Verse.TickManager)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Game.UpdatePlay_Patch4 (Verse.Game)
Verse.Root_Play:Update ()```

Not sure how to read that, a problem with PerformanceOptimizer?

**Comment by Sn1p3rr3c0n** [comment] 2024-09-01 17:31
FYI the start and end of the code block should be on their own Line.

The error clearly indicates that the issue is caused by `ImP.ImpCore.GetRoleEffectQualityOffset`.

I'm not sure why you would suspect `PerformanceOptimizer`.

What is `ImP.ImpCore`? That I can't tell you with the provided information. That info would be included in a HugsLib log. 
https://github.com/zymex22/Project-RimFactory-Revived/wiki/How-to-Report#a-hugslib-log

**Comment by sdfg2** [comment] 2024-09-01 19:23
Thank you very much for your quick response, and helping me along.  I just didn't know where to look further.  

I investigated and found that ImP is [I'm Proud of It!](https://steamcommunity.com/sharedfiles/filedetails/?id=3305125244&searchtext=i%27m+proud).  I removed that mod and everything works now.  I guess it makes sense, I think ImP must be looking for a pawn who made the item or something.

**Comment by Sn1p3rr3c0n** [comment] 2024-09-05 15:47
Caused by another mod. Closing

**Closed by Sn1p3rr3c0n** 2024-09-05 15:47 UTC
